### ISSUE TITLE
cant subscribe.  warn: some of subscriptions failed: 

### ISSUE THREAD

**Issue by gingazov2010** [yandex-cloud/examples#13]
здравствуйте, возникла проблема, я создал сертификат x509 и к нему ключ, скачал root_ca.cert с вашего сайта. используя MQTT.fx указал tls 1.2 root сертификат и ключ, подключил к облаку, подписался на топик $devices/xxxbtj1hsr7o1h9l9xxx/commands успешно, а вот при попытке подписки на топик $devices/xxxbtj1hsr7o1h9l9xxx/events у меня в логе появляется ошибка:
warn: some of subscriptions failed: not allowed to subscribe to ["$devices/xxxbtj1hsr7o1h9l9xxx/events"]; clientID: 123321456654

нет разрешения, как обойти эту проблему? или я что-то делаю не так? и самое главное где ваши примеры для stm32 или espressif esp32 bkb esp8266? у всех iot сервисов таковые имеются . до этого использовал AWS IOT там очень много примеров.

**Comment by gingazov2010** [comment]
заработало по такой схеме,
создал реестр, затем создал устройство.
mqtt клиент подключил при помощи сертификата и ключа на реестр, а устройство подключил при помощи логина и пароля устройства.
отправлять команды можно подключившись mqtt клиентом к реестру, в топик устройства $devices/xxxxtj1hsr7o1h9lxxxx/commands
а подписываться клиентом можно на топик $devices/xxxxtj1hsr7o1h9lxxxx/events

**Comment by gingazov2010** [comment]
и пример кода для esp12e, спасибо Александру Суркову
Менеджер по развитию бизнеса в направлении IoT в Яндекс.Облаке
код на скорую руку но работает.
`
#include <dummy.h>
#include <ESP8266WiFi.h>
#include <PubSubClient.h>
#include <MQTT.h>

const char* ssid = "wifi sid";
const char* password = "pass";

const char* mqttserver = "130.193.44.244";        //mqtt.cloud.yandex.net
String deviceSerial = "xxxxtj1hsr7o1h9lxxxx";     //Yandex IoT Core Device ID
const char* mqttuser = "xxxxtj1hsr7o1h9lxxxx";    //Yandex IoT Core Cloud Device ID
const char* mqttpassword = "password";  //Yandex IoT Core Device pawssword
const int mqttport=8883;
                                                  //String deviceType = "$devices/<ID устройства>/commands";

String topicCommandId = String("$devices/")+deviceSerial+String("/commands/#");
String topicEventsId = String("$devices/")+deviceSerial+String("/events");
bool isOnn=false;
const char* test_root_ca = \
"-----BEGIN CERTIFICATE-----\n \
MIIFGTCCAwGgAwIBAgIQJMM7ZIy2SYxCBgK7WcFwnjANBgkqhkiG9w0BAQ0FADAf\
MR0wGwYDVQQDExRZYW5kZXhJbnRlcm5hbFJvb3RDQTAeFw0xMzAyMTExMzQxNDNa\
Fw0zMzAyMTExMzUxNDJaMB8xHTAbBgNVBAMTFFlhbmRleEludGVybmFsUm9vdENB\
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAgb4xoQjBQ7oEFk8EHVGy\
1pDEmPWw0Wgw5nX9RM7LL2xQWyUuEq+Lf9Dgh+O725aZ9+SO2oEs47DHHt81/fne\
5N6xOftRrCpy8hGtUR/A3bvjnQgjs+zdXvcO9cTuuzzPTFSts/iZATZsAruiepMx\
SGj9S1fGwvYws/yiXWNoNBz4Tu1Tlp0g+5fp/ADjnxc6DqNk6w01mJRDbx+6rlBO\
aIH2tQmJXDVoFdrhmBK9qOfjxWlIYGy83TnrvdXwi5mKTMtpEREMgyNLX75UjpvO\
NkZgBvEXPQq+g91wBGsWIE2sYlguXiBniQgAJOyRuSdTxcJoG8tZkLDPRi5RouWY\
gxXr13edn1TRDGco2hkdtSUBlajBMSvAq+H0hkslzWD/R+BXkn9dh0/DFnxVt4XU\
5JbFyd/sKV/rF4Vygfw9ssh1ZIWdqkfZ2QXOZ2gH4AEeoN/9vEfUPwqPVzL0XEZK\
r4s2WjU9mE5tHrVsQOZ80wnvYHYi2JHbl0hr5ghs4RIyJwx6LEEnj2tzMFec4f7o\
dQeSsZpgRJmpvpAfRTxhIRjZBrKxnMytedAkUPguBQwjVCn7+EaKiJfpu42JG8Mm\
+/dHi+Q9Tc+0tX5pKOIpQMlMxMHw8MfPmUjC3AAd9lsmCtuybYoeN2IRdbzzchJ8\
l1ZuoI3gH7pcIeElfVSqSBkCAwEAAaNRME8wCwYDVR0PBAQDAgGGMA8GA1UdEwEB\
/wQFMAMBAf8wHQYDVR0OBBYEFKu5xf+h7+ZTHTM5IoTRdtQ3Ti1qMBAGCSsGAQQB\
gjcVAQQDAgEAMA0GCSqGSIb3DQEBDQUAA4ICAQAVpyJ1qLjqRLC34F1UXkC3vxpO\
nV6WgzpzA+DUNog4Y6RhTnh0Bsir+I+FTl0zFCm7JpT/3NP9VjfEitMkHehmHhQK\
c7cIBZSF62K477OTvLz+9ku2O/bGTtYv9fAvR4BmzFfyPDoAKOjJSghD1p/7El+1\
eSjvcUBzLnBUtxO/iYXRNo7B3+1qo4F5Hz7rPRLI0UWW/0UAfVCO2fFtyF6C1iEY\
/q0Ldbf3YIaMkf2WgGhnX9yH/8OiIij2r0LVNHS811apyycjep8y/NkG4q1Z9jEi\
VEX3P6NEL8dWtXQlvlNGMcfDT3lmB+tS32CPEUwce/Ble646rukbERRwFfxXojpf\
C6ium+LtJc7qnK6ygnYF4D6mz4H+3WaxJd1S1hGQxOb/3WVw63tZFnN62F6/nc5g\
6T44Yb7ND6y3nVcygLpbQsws6HsjX65CoSjrrPn0YhKxNBscF7M7tLTW/5LK9uhk\
yjRCkJ0YagpeLxfV1l1ZJZaTPZvY9+ylHnWHhzlq0FzcrooSSsp4i44DB2K7O2ID\
87leymZkKUY6PMDa4GkDJx0dG4UXDhRETMf+NkYgtLJ+UIzMNskwVDcxO4kVL+Hi\
Pj78bnC5yCw8P5YylR45LdxLzLO68unoXOyFz1etGXzszw8lJI9LNubYxk77mK8H\
LpuQKbSbIERsmR+QqQ==\
-----END CERTIFICATE-----\n";


int in1 = D5; // gpio14
int in2 = D6; // gpio12
int in3 = D7; // gpio13

WiFiClientSecure  net;
PubSubClient client(net);
BearSSL::X509List x509(test_root_ca);

unsigned long lastMillis = 0;


////////////////////////////////////////////////////////////////////////////////////////////////////////////
void connect() {
  delay(5000);
  Serial.print("\nchecking wifi...");
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print("w");
    delay(1000);
  }
  
net.setInsecure();

Serial.print("\nconnecting...");
  String resDevName =  deviceSerial;
  Serial.print(resDevName.c_str());
  while (!client.connect(resDevName.c_str(), mqttuser, mqttpassword)) {
     Serial.print(".");
     delay(1000);
  }

 if (client.publish(topicEventsId.c_str(), deviceSerial.c_str())) {
      Serial.println("\nPublish ok");
    }
    else {
      Serial.println("\nPublish failed");
    }

    
Serial.println("\nConnected to MQTT broker");
  String topicCommandId = String("$devices/")+deviceSerial+String("/commands/#");
  Serial.print("\n subscribe to: ");
  Serial.println(topicCommandId.c_str());
 client.subscribe(topicCommandId.c_str());

  digitalWrite(LED_BUILTIN, HIGH); //Синий
 
}
///////////////////////////////////////////////////////////////////////////////////////////////////////////


void messageReceived(char* topic, byte* payload, unsigned int length) {

 String topicString = String(topic);
 Serial.print("Find topic: ");
                             
 Serial.println(topicString.c_str());
 Serial.print("Find command: ");
   int lstIndexSlash  =topicString.lastIndexOf('/');
  String topicCommand =topicString.substring(lstIndexSlash+1);
 Serial.println(topicCommand.c_str());
Serial.print("check...");
Serial.print("\n");
                            
 //String strPayload = String((char*)payload);
 //Serial.print(strPayload);
 //Serial.print("\n");

    payload[length] = '\0';
    Serial.print("payload: [");
    Serial.print((char *)payload);
    Serial.println("]");


    String command = (char *)payload;
    
     if (command.startsWith("green.on")){
      Serial.println("Green on!");
      digitalWrite(in1, HIGH);
      client.publish(topicEventsId.c_str(), "green on done");
      return;
    }

   else if (command.startsWith("green.off")){
      Serial.println("Green off!");
      digitalWrite(in1,LOW);
      client.publish(topicEventsId.c_str(), "green off done");
      return;
    }

   else if (command.startsWith("red.on")){
      Serial.println("Red on!");
      digitalWrite(in2,HIGH);
      client.publish(topicEventsId.c_str(), "red on done");
      return;
    }

    else if (command.startsWith("red.off")){
      Serial.println("Red off!");
      digitalWrite(in2,LOW);
      client.publish(topicEventsId.c_str(), "red off done");
      return;
    }

    else if (command.startsWith("yellow.on")){
      Serial.println("Yellow on!");
      digitalWrite(in3,HIGH);
      client.publish(topicEventsId.c_str(), "yellow on done");
      return;
    }

    else if (command.startsWith("yellow.off")){
      Serial.println("Yellow off!");
      digitalWrite(in3,LOW);
      client.publish(topicEventsId.c_str(), "yellow off done");
      return;
    }

    else{
    Serial.println("Not found command");
    client.publish(topicEventsId.c_str(), "Not found command");
    }
}
//////////////////////////////////////////////////////////////////////////////////////////////////////////
void setup() {

 Serial.begin(9600);
  delay(100);
  Serial.print("\n");
 Serial.print("go");
  pinMode(in1, OUTPUT);
  pinMode(in2, OUTPUT);
  pinMode(in3, OUTPUT);
  pinMode(LED_BUILTIN, OUTPUT);

 //digitalWrite(in1, HIGH);
 //digitalWrite(in2, HIGH);
 //digitalWrite(in3, HIGH);
 digitalWrite(LED_BUILTIN, HIGH);

delay(1000);

 digitalWrite(in1, LOW);
 digitalWrite(in2, LOW);
 digitalWrite(in3, LOW);
 digitalWrite(LED_BUILTIN, LOW);
 


 WiFi.begin(ssid, password);
 client.setServer(mqttserver, mqttport);
  client.setCallback(messageReceived);
connect();
 
}

  



void loop() {
  
  client.loop();

  if (!client.connected()) {
    connect();
  }

}`

**Comment by YandexIoT** [comment]
Спасибо за Ваш развернутый ответ здесь, да мы для ускорения решения Вашей проблемы предпочли разобраться через почту.
Как я понимаю, на текущий момент Ваша проблема решена.
По поводу примеров, как мы и ответили в письмах - в данный момент в разработке.
