### ISSUE TITLE
Проблема с окружением после создания версии  функции

### ISSUE THREAD

**Issue by sergkit** [yandex-cloud/examples#91]
После создания версии  функции  из тестового примера  [examples](https://github.com/yandex-cloud/examples)/[serverless](https://github.com/yandex-cloud/examples/tree/master/serverless)/[functions](https://github.com/yandex-cloud/examples/tree/master/serverless/functions)/YDB-connect-from-serverless-function/
при запуске тестирования ошибка  (Среда выполнения  node js  16, функция запускается в облаке)
`
{
    "errorMessage": "Cannot find module '../package.json'\nRequire stack:\n- /function/code/node_modules/ydb-sdk/build/cjs/version.js\n- /function/code/node_modules/ydb-sdk/build/cjs/utils.js\n- /function/code/node_modules/ydb-sdk/build/cjs/discovery.js\n- /function/code/node_modules/ydb-sdk/build/cjs/driver.js\n- /function/code/node_modules/ydb-sdk/build/cjs/index.js\n- /function/code/database.js\n- /function/code/index.js",
    "errorType": "Error",
    "stackTrace": [
        {
            "line": "Require stack:"
        },
        {
            "line": "- /function/code/node_modules/ydb-sdk/build/cjs/version.js"
        },
        {
            "line": "- /function/code/node_modules/ydb-sdk/build/cjs/utils.js"
        },
        {
            "line": "- /function/code/node_modules/ydb-sdk/build/cjs/discovery.js"
        },
        {
            "line": "- /function/code/node_modules/ydb-sdk/build/cjs/driver.js"
        },
        {
            "line": "- /function/code/node_modules/ydb-sdk/build/cjs/index.js"
        },
        {
            "line": "- /function/code/database.js"
        },
        {
            "line": "- /function/code/index.js"
        },
        {
            "function": "Function.Module._resolveFilename",
            "file": "node:internal/modules/cjs/loader",
            "line": 933,
            "column": 15
        },
        {
            "function": "Function.Module._load",
            "file": "node:internal/modules/cjs/loader",
            "line": 778,
            "column": 27
        },
        {
            "function": "Module.require",
            "file": "node:internal/modules/cjs/loader",
            "line": 1005,
            "column": 19
        },
        {
            "function": "require",
            "file": "node:internal/modules/cjs/helpers",
            "line": 102,
            "column": 18
        },
        {
            "function": "Object.<anonymous>",
            "file": "/function/code/node_modules/ydb-sdk/build/cjs/version.js",
            "line": 4,
            "column": 17
        },
        {
            "function": "Module._compile",
            "file": "node:internal/modules/cjs/loader",
            "line": 1103,
            "column": 14
        },
        {
            "function": "Object.Module._extensions..js",
            "file": "node:internal/modules/cjs/loader",
            "line": 1157,
            "column": 10
        },
        {
            "function": "Module.load",
            "file": "node:internal/modules/cjs/loader",
            "line": 981,
            "column": 32
        },
        {
            "function": "Function.Module._load",
            "file": "node:internal/modules/cjs/loader",
            "line": 822,
            "column": 12
        },
        {
            "function": "Module.require",
            "file": "node:internal/modules/cjs/loader",
            "line": 1005,
            "column": 19
        }
    ]
}
`

**Comment by gayratv** [comment]
Спасибо за замечание, issue принят в работу, в течение пары дней починю.
Проблема кроется в одном из изменений SDK, на 3.0 код работал, с перерходом на latest (3.3.1) код почему то перестал работать, а ведь он был опубликован всего месяц назад.

**Comment by sergkit** [comment]
Не знаю, что случилось, но сейчас все опять  заработало.  Закрываю issue
